name: gestion_carburant
description: "Pour la gestion de carburant et la gestion de flotte"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

# The following section is for the Dart SDK version.
# It specifies the minimum Dart SDK version required for the project.
environment:
  sdk: ^3.6.0

# The following section is for the Flutter package configuration.
# It includes the necessary dependencies for the project.
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  http: ^0.13.5
  flutter_launcher_icons: ^0.13.1
  qr_flutter: ^4.1.0

  cupertino_icons: ^1.0.8
  fl_chart: ^0.71.0

# The following dependencies are used for state management and local storage.
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/solde.json

# The following section is specific to Flutter Launcher Icons.
# It generates app icons for both Android and iOS platforms.
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
