// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtrPvf92smtS-sWK-wcHzC1SXPE4gdPkU',
    appId: '1:343645363397:web:7f2f055b1445942feae4ac',
    messagingSenderId: '343645363397',
    projectId: 'erp-banamur',
    authDomain: 'erp-banamur.firebaseapp.com',
    storageBucket: 'erp-banamur.appspot.com',
    measurementId: 'G-ZD1M6XSS0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgdn64ix9ZGsvshS2RfgpSCVSDXaks-V0',
    appId: '1:343645363397:android:672bf4ec0ab1e16ceae4ac',
    messagingSenderId: '343645363397',
    projectId: 'erp-banamur',
    storageBucket: 'erp-banamur.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW2d_kWQs7eIEoSnRAoOfGM7hpuwcXFv4',
    appId: '1:343645363397:ios:9b7ddc856d6b5433eae4ac',
    messagingSenderId: '343645363397',
    projectId: 'erp-banamur',
    storageBucket: 'erp-banamur.appspot.com',
    iosBundleId: 'com.example.gestionCarburant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW2d_kWQs7eIEoSnRAoOfGM7hpuwcXFv4',
    appId: '1:343645363397:ios:9b7ddc856d6b5433eae4ac',
    messagingSenderId: '343645363397',
    projectId: 'erp-banamur',
    storageBucket: 'erp-banamur.appspot.com',
    iosBundleId: 'com.example.gestionCarburant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtrPvf92smtS-sWK-wcHzC1SXPE4gdPkU',
    appId: '1:343645363397:web:54c10ee64257d67ceae4ac',
    messagingSenderId: '343645363397',
    projectId: 'erp-banamur',
    authDomain: 'erp-banamur.firebaseapp.com',
    storageBucket: 'erp-banamur.appspot.com',
    measurementId: 'G-6H9XRED464',
  );
}
